In [4]:
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self,num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3 , 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out


In [5]:
# create dataset
features = torch.rand(10,5)
# create a model
model = Model(features.shape[1])
#call model for forward pass
model(features)


tensor([[0.5083],
        [0.5182],
        [0.5323],
        [0.5059],
        [0.5171],
        [0.4978],
        [0.5028],
        [0.4997],
        [0.5047],
        [0.5013]], grad_fn=<SigmoidBackward0>)

In [7]:
# show model weights
model.linear1.weight

Parameter containing:
tensor([[ 0.1352,  0.1901, -0.0236,  0.1449, -0.4135],
        [ 0.1913, -0.1912,  0.0635, -0.3926, -0.3945],
        [-0.1488,  0.2353,  0.0631,  0.2062, -0.2058]], requires_grad=True)

In [8]:
# show model weights
model.linear2.weight

Parameter containing:
tensor([[ 0.5761, -0.3890, -0.0952]], requires_grad=True)

In [9]:
#show bias
model.linear1.bias

Parameter containing:
tensor([-0.0445, -0.4226,  0.3639], requires_grad=True)

In [10]:
#show bias
model.linear2.bias

Parameter containing:
tensor([0.0451], requires_grad=True)

In [12]:
# show the structure of model
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00