In [3]:
# Creating model class
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__ (self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out
    

In [4]:
# create dataset
features = torch.rand(10,5)
# create a model
model = Model(features.shape[1])
#call model for forward pass
model(features)


tensor([[0.5283],
        [0.6308],
        [0.4970],
        [0.5120],
        [0.5178],
        [0.5445],
        [0.5648],
        [0.5364],
        [0.5184],
        [0.5740]], grad_fn=<SigmoidBackward0>)

In [6]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.4293, -0.2392,  0.4018,  0.1531, -0.2354]], requires_grad=True)

In [7]:
#show bias
model.linear.bias

Parameter containing:
tensor([-0.1211], requires_grad=True)

In [9]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00