In [8]:
import torch
print(torch.__version__)

2.11.0+cu128


In [9]:
if torch.cuda.is_available():
    print("CUDA is available. You can use GPU acceleration.")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available. Using CPU.")

CUDA is available. You can use GPU acceleration.
Using GPU: NVIDIA GeForce RTX 4050 Laptop GPU


# Creating a Tensor



In [10]:
# Using empty
x = torch.empty(3, 4)
print(x)

tensor([[2.7975e-17, 9.1225e-43, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [11]:
# check type
print(type(x))

<class 'torch.Tensor'>


In [12]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
torch.rand(2, 3)

tensor([[0.6902, 0.9207, 0.7482],
        [0.1726, 0.7945, 0.3674]])

In [16]:
#manual_seed
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [18]:

torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [19]:
torch.Tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [22]:
# Other ways

# arange
print("Using arange:", torch.arange(1, 10, 2))
# using linspace
print("Using linspace:", torch.linspace(0, 10,10))
# using eye
print("Using eye:", torch.eye(5))
# using full
print("Using full:", torch.full((3, 3), 7))

Using arange: tensor([1, 3, 5, 7, 9])
Using linspace: tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye: tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full: tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])


# Tensor Shapes


In [31]:
x = torch.Tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [25]:
x.shape

torch.Size([2, 3])

In [26]:
torch.empty_like(x)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [27]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [28]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [46]:
torch.rand_like(x, dtype=torch.float64)

tensor([[0.5522, 0.9559, 0.9405],
        [0.2215, 0.3271, 0.1352]], dtype=torch.float64)

# Tensor Data Types

In [32]:
x.dtype

torch.float32

In [37]:
torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0 ]], dtype=torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [40]:
torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [44]:
x = x.to(torch.int32)

# Mathamatical Operation


1. Scalar Problem

In [47]:
x = torch.rand(3, 4)
print(x)

tensor([[0.9535, 0.7064, 0.1629, 0.8902],
        [0.5163, 0.0359, 0.6476, 0.3430],
        [0.3182, 0.5261, 0.0447, 0.5123]])


In [52]:
# addition
x+2
# subtraction
x-2
# multiplication    
x*2
# division
x/2
# integer division
(x*100)//3
# mod
((x*100)//3)%2
# power
(x*100)**2

tensor([[9092.3145, 4990.0518,  265.2933, 7924.5244],
        [2665.3604,   12.8770, 4194.2817, 1176.6658],
        [1012.7684, 2767.6826,   19.9440, 2625.0046]])

In [ ]:
a = torch.rand(3, 4)
b = torch.rand(3, 4)
print("a:", a)
print("b:", b)


a: tensor([[0.9051, 0.5989, 0.4450, 0.7278],
        [0.4563, 0.3389, 0.6211, 0.5530],
        [0.6896, 0.3687, 0.9053, 0.8356]])
b: tensor([[0.3039, 0.6726, 0.5740, 0.9233],
        [0.9178, 0.7590, 0.7775, 0.6179],
        [0.3379, 0.2170, 0.9454, 0.7116]])
a + b: tensor([[1.2090, 1.2715, 1.0190, 1.6511],
        [1.3741, 1.0979, 1.3987, 1.1709],
        [1.0275, 0.5858, 1.8506, 1.5471]])


In [55]:
print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)

a + b: tensor([[1.2090, 1.2715, 1.0190, 1.6511],
        [1.3741, 1.0979, 1.3987, 1.1709],
        [1.0275, 0.5858, 1.8506, 1.5471]])
a - b: tensor([[ 0.6012, -0.0738, -0.1290, -0.1955],
        [-0.4615, -0.4202, -0.1564, -0.0649],
        [ 0.3517,  0.1517, -0.0401,  0.1240]])
a * b: tensor([[0.2751, 0.4028, 0.2554, 0.6720],
        [0.4188, 0.2572, 0.4830, 0.3417],
        [0.2330, 0.0800, 0.8558, 0.5946]])
a / b: tensor([[2.9782, 0.8903, 0.7753, 0.7883],
        [0.4971, 0.4464, 0.7989, 0.8950],
        [2.0410, 1.6990, 0.9576, 1.1743]])


In [57]:
c = torch.tensor([1,-2,3,-4])
torch.abs(c)
torch.neg(c)

tensor([-1,  2, -3,  4])

In [63]:
d = torch.tensor([1.6, 2.2, 3.7, 4.1])


In [64]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [65]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [66]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [67]:
torch.clamp(d, min=2.0, max=3)

tensor([2.0000, 2.2000, 3.0000, 3.0000])

<!-- Reduction Operation -->

# Reduction Operation

In [93]:
e = torch.randint(size=(3, 3), low=0, high=10, dtype=torch.float32)
e

tensor([[2., 5., 6.],
        [1., 4., 5.],
        [6., 9., 2.]])

In [94]:
torch.sum(e)


tensor(40.)

In [95]:
torch.sum(e, dim=0)


tensor([ 9., 18., 13.])

In [96]:
torch.sum(e, dim=1)


tensor([13., 10., 17.])

In [97]:
torch.mean(e)

tensor(4.4444)

In [98]:
torch.mean(e, dim=0)

tensor([3.0000, 6.0000, 4.3333])

In [99]:
torch.median(e)

tensor(5.)

In [100]:
torch.max(e)
torch.min(e)

tensor(1.)

In [101]:
torch.prod(e)

tensor(129600.)

In [102]:
torch.std(e)

tensor(2.5055)

In [103]:
torch.var(e)

tensor(6.2778)

In [104]:
torch.argmax(e)

tensor(7)

In [105]:
torch.argmin(e)

tensor(3)

# matrix operation

In [107]:
f = torch.randint(size=(2,3), low=0, high=10 )
g = torch.randint(size=(3,2), low=0, high=10)
print("f:", f)
print("g:", g)

f: tensor([[8, 4, 9],
        [0, 7, 9]])
g: tensor([[2, 7],
        [0, 2],
        [4, 4]])


In [108]:
# matrix multiplication
torch.matmul(f, g)

tensor([[ 52, 100],
        [ 36,  50]])

In [110]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

torch.dot(vector1, vector2)

tensor(11)

In [114]:
f
torch.transpose(f, 0, 1)

tensor([[8, 0],
        [4, 7],
        [9, 9]])

In [118]:
torch.det(x)

RuntimeError: linalg.det: A must be batches of square matrices, but they are 3 by 4 matrices